# 1. Data Cleaning

## 1.1 Import and Data

In [3]:
import pandas as pd
import numpy as np

df = pd.read_excel('Superstore.xls')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

## 1.2 Initial Exploration

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

## 1.3 Dataset Shape

In [7]:
df.shape

(10194, 21)

## Checking Null Values

In [9]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

## Checking duplicates

In [11]:
df.duplicated().sum()

0

## Check Data types

In [13]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

##  Logical Error Checks

In [15]:
(df['Sales'] < 0).sum()

0

In [16]:
(df['Quantity'] < 0).sum()

0

In [17]:
(df['Discount'] > 1).sum()

0

In [18]:
(df['Ship Date'] < df['Order Date']).sum()

0

In [19]:
df['Discount'].describe()

count    10194.000000
mean         0.155385
std          0.206249
min          0.000000
25%          0.000000
50%          0.200000
75%          0.200000
max          0.800000
Name: Discount, dtype: float64

In [20]:
df['Profit'].describe()

count    10194.000000
mean        28.673417
std        232.465115
min      -6599.978000
25%          1.760800
50%          8.690000
75%         29.297925
max       8399.976000
Name: Profit, dtype: float64

## Worst losses

In [22]:
df.nsmallest(10, 'Profit')[['Order ID','Product Name','Category','Sales', 'Discount', 'Profit']]

,Order ID,Product Name,Category,Sales,Discount,Profit
6398,US-2025-108196,Cubify CubeX 3D Printer Double Head Print,Technology,4499.985,0.7,-6599.9780
9318,US-2026-168116,Cubify CubeX 3D Printer Triple Head Print,Technology,7999.980,0.5,-3839.9904
821,US-2023-169019,GBC DocuBind P400 Electric Binding System,Office Supplies,2177.584,0.8,-3701.8928
7441,US-2026-134845,Lexmark MX611dhe Monochrome Laser Printer,Technology,2549.985,0.7,-3399.9800
9845,US-2026-122714,Ibico EPK-21 Electric Binding System,Office Supplies,1889.990,0.8,-2929.4845
4037,US-2024-147830,Cubify CubeX 3D Printer Double Head Print,Technology,1799.994,0.7,-2639.9912
9557,US-2026-131254,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,1525.188,0.8,-2287.7820
2108,US-2024-116638,Chromcraft Bull-Nose Wood Oval Conference Tabl...,Furniture,4297.644,0.4,-1862.3124
4570,US-2025-130946,GBC DocuBind P400 Electric Binding System,Office Supplies,1088.792,0.8,-1850.9464
226,US-2023-145317,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,0.5,-1811.0784

## Best profits

In [24]:
df.nlargest(10, 'Profit')[['Order ID','Product Name','Category','Sales', 'Discount', 'Profit']]

,Order ID,Product Name,Category,Sales,Discount,Profit
5894,US-2025-118689,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,0.0,8399.9760
7255,US-2026-140151,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,0.0,6719.9808
9517,US-2026-166709,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,0.0,5039.9856
6674,US-2025-117121,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,0.0,4946.3700
1203,US-2023-116904,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,0.0,4630.4755
9171,US-2026-127180,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,0.2,3919.9888
2242,US-2024-145352,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,6354.950,0.0,3177.4750
4282,US-2025-158841,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,0.0,2799.9840
5907,US-2025-140158,Hewlett Packard LaserJet 3310 Copier,Technology,5399.910,0.0,2591.9568
6882,US-2026-138289,GBC DocuBind P400 Electric Binding System,Office Supplies,5443.960,0.0,2504.2216

## High discount orders — are they profitable?

In [26]:
df[df['Discount'] >= 0.5]['Profit'].describe()

count     940.000000
mean     -103.762359
std       379.791428
min     -6599.978000
25%       -48.392000
50%       -13.431500
75%        -4.958700
max        -0.596400
Name: Profit, dtype: float64

## Create new columns
### 1-Shipping Days
### 2-Profit Margin
### 3-Year, Month, Year-Month

In [28]:
df['Shipping_Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [29]:
df['Profit_Margin'] = df['Profit'] / df['Sales']

In [30]:
df['Year'] = df['Order Date'].dt.year

In [31]:
df['Month'] = df['Order Date'].dt.month

In [32]:
df['Year_Month'] = df['Order Date'].dt.to_period('M').astype(str)

In [56]:
df.to_csv('clean_sales.csv', index=False)

In [58]:
df.to_csv('C:/Users/aziza/Downloads/clean_sales.csv', index=False)